# Generated by Django 3.1.7 on 2021-03-10 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ArticlePost',
        ),
    ]
