# Generated by Django 3.1.7 on 2021-03-11 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210310_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='likes',
            field=models.ManyToManyField(related_name='article_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
