# Generated by Django 3.1.7 on 2021-03-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210311_1125'),
        ('posts', '0004_articlepost_likes'),
    ]

    operations = [
    ]
