# Generated by Django 3.1.7 on 2021-03-15 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_merge_20210312_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='likes',
            field=models.ManyToManyField(related_name='user_article_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
