# Generated by Django 3.1.7 on 2021-03-15 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='song_image'),
            preserve_default=False,
        ),
    ]
