# Generated by Django 3.1.7 on 2021-03-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210315_1043'),
        ('posts', '0009_auto_20210315_1145'),
    ]

    operations = [
    ]
