# Generated by Django 3.1.7 on 2021-03-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210316_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=13),
        ),
    ]
