# Generated by Django 3.1.7 on 2021-03-11 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210309_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
