# Generated by Django 3.1.7 on 2021-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210318_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='{% static/images/default.png %}', upload_to='profile_image'),
        ),
    ]
